name: invitations
dependencies:
- boto3=1.4.8
- botocore=1.8.5
- configargparse=0.12.0
- mypy=0.550
- pip
- pytest=3.3.2
- python=3.6.4
- setuptools
- toolz=0.9.0
- pip:
  - wedding (/Users/jesse/Code/python/wedding)==0.1
  - google-api-python-client==1.6.5
  - google-auth==1.4.0
  - google-auth-oauthlib==0.2.0
  - oauthlib==2.0.6
  - pystache==0.5.4
